### ISSUE TITLE
User Encountered Error message

### ISSUE THREAD

**Issue by ohwowmarketing** [ohwowmarketing/bracket#11]
User encountered error message...will email screengrab of message

**Comment by moseley** [comment]
Error message, "Value at 'username' failed to satisfy constraint. Member must satisfy regular expression pattern: `[\p{l}\p{m}\p{s}\p{n}\p{p}]+`

**Comment by moseley** [comment]
This pattern is requiring that a username cannot contain spaces. A  more user friendly message is replaced in commit 80b027bfc035e790d6d8f3407500e5cb45918c8c
