### ISSUE TITLE
State Field Title

### ISSUE THREAD

**Issue by ohwowmarketing** [ohwowmarketing/bracket#13]
Users are having issues because they are trying to type in the full name of the state.  Can we change the title of the field from State to State Abbreviation ---- so people know to use abbreviation

**Comment by moseley** [comment]
Label updated on commit [e993c5aebdcc970300fc47bfeef7d3c34b871f6d](https://github.com/ohwowmarketing/bracket/commit/e993c5aebdcc970300fc47bfeef7d3c34b871f6d)
